name: Deploy to Main

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # 在这里执行打包操作，将博客文件打包到一个文件夹或压缩文件中
          # 例如，在这里可以执行类似以下命令：
          # npm install
          # npm run build
          # tar -czvf blog.tar.gz dist/

      - name: Push to Main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
